
work_dir: ./work_dir/ntu/xsub/ase_test

# feeder
feeder: feeders.feeder.Feeder

test_feeder_args:
  data_path: ../MS-G3D/data/ntu/xsub/val_data_joint.npy
  label_path: ../MS-G3D/data/ntu/xsub/val_label.pkl

# model
model: model.network.Model
model_args:
  in_channels: 15
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30,40,50]

num_epoch: 60
device: [0]
batch_size: 40
forward_batch_size: 40
test_batch_size: 40
nesterov: True

optimizer: SGD

eval_start: 5
eval_interval: 5

phase: test
weights: ./work_dir/ntu/xsub/ase_train/2023-05-19T17-25-37/weights/weights-epoch-best_model_35.pt
save_score: True
